### ISSUE TITLE
403 error on Framacarte

### ISSUE THREAD

**Issue by MaiaDereva** [umap-project/umap#2852]
Hello,

Clone of my map: https://framacarte.org/m/212912/
I'm using Librewolf 141.0-1 on Linux Mint 21.3 Cinnamon 6.0.4 / 5.15.0-151-generic

Steps
- I created a umap map via framacarte, i.e. logged in with my OSM account.
- I entered points for two hours (and regularly saved my work)
- I saved, went back to the maps list, and clicked on the ‘Share’ button.
- A 403 error appeared, and I can no longer see any of the points I entered.
- I tried logging out and logging back in, but I still get this error. What should I do to recover my entries?

Also, I tried to create another map to reproduce the error. The 403 error appeared without clicking the "Share" button: https://framacarte.org/m/212914/

Printscreen : 

<img width="175" height="95" alt="Image" src="https://github.com/user-attachments/assets/f2e65d1d-b5f5-4f0a-9df0-de01e137354f" />

Thank you for your help.

**Comment by yohanboniface** [comment]
> Also, I tried to create another map to reproduce the error. The 403 error appeared without clicking the "Share" button: https://framacarte.org/m/212914/

Can you detail what you have done in this map so I'll try to reproduce ?

**Comment by MaiaDereva** [comment]
Hi @yohanboniface , I created the map, named it, saved it, modify the access to "Anyone with link", saved, added a point on London, saved, came back to the list, clicked (went back using the link in the list) on the map again : there is no point and a 403 error.

Done again with a TEST2 map in order to be sure of the steps: https://framacarte.org/m/212916/

**Comment by yohanboniface** [comment]
Weird, I cannot reproduce https://framacarte.org/fr/map/test-pouet_212917#6/51.000/2.000

But I do see the 403 on your maps, tough…

**Comment by yohanboniface** [comment]
Ok sorry, now I can reproduce. It's related to the permissions change. I'm investigating.

**Comment by yohanboniface** [comment]
Another weird part is that I can only reproduce on Framacarte, not locally nor on OSM server or the development server.

@ldidry any idea ? can it be that you have some custom (or old ?) settings / middlewares that could impact ?

**Comment by ldidry** [comment]
We have some permissions issues on framacarte : gzipped version of json data are created with rights 600 while the json data has rights 644 (or 640, I don’t remember).
With right 600, nginx (user `www-data`) can’t read the gzipped data (which belongs to user `umap`).

We normally have a daily cron to fix the rights.

I should have created a ticket for this problem, but didn’t find time before my vacations (NB: still in vacations).

Ping @SansPseudoFix for information

**Comment by MaiaDereva** [comment]
Thank you @ldidry . There's no worry about my map, enjoy your vacation.

If I understand well your message, I should have my rights back and recover all the bullets after the daily cron? If this is the expected behaviour, then there is also a problem with the cron because I still get the 403 error two days later.

**Comment by ldidry** [comment]
Well, there was no cron. I guess it was because my command line to fix the problem took a lot of time and needed to be better (a `find` command) before using it regularly.

Now, it takes less than 5 seconds, and I added it as a every-minute cron job.

If it’s not working now, I’ll let my co-workers investigate.

**Comment by yohanboniface** [comment]
And when you're back from vacations, let's understand what's going on to fix that in the first place :)

**Comment by MaiaDereva** [comment]
It seems to work for a new map: https://framacarte.org/en/map/test-5_213072
But not for an older one: https://framacarte.org/en/map/test-3_212980

**Comment by Chocobozzz** [comment]
Hi,

(I work for Framasoft)

I added a fix to the cron script to also change directories rights (`x` was missing on some of them)

**Comment by MaiaDereva** [comment]
Hello @Chocobozzz , thank you for your fix. It works for new maps, but there is still a 403 error on my initial map (see first post) and old test maps. Is there a way to retrieve my data by taking some kind of action, or should I make a new map?

**Comment by Chocobozzz** [comment]
> but there is still a 403 error on my initial map 

Thanks, it should be fixed now.

**Comment by MaiaDereva** [comment]
Great! It works, thank you :)
(I delete the cloned map because the data is a little bit personal ^^)

**Comment by yohanboniface** [comment]
@Chocobozzz thanks! Do you have any details to help fixing the issue in uMap itself (if it makes sense) ?

**Comment by Chocobozzz** [comment]
`x` right was missing on directories too, so nginx can traverse umap directories and correctly serve the files

**Comment by ldidry** [comment]
@yohanboniface We migrated Framacarte to another server (not enough space anymore), same setup, but with fresh new `umap` user and virtualenv, we still have the problem.
NB: the new server runs on Trixie, the old was on Bookworm.

We run `umap.service` (with uvicorn) with the user `umap` which belongs to the group `www-data`.

The problem is with the group permissions on created folders and gzipped version of geojson files.

For the gzipped version of geojson files: `os.chmod(to_path, stat.S_IRGRP)` added to the `gzip_file` of [`utils.py`](https://github.com/umap-project/umap/blob/master/umap/utils.py#L146) should do the job (I just patched Framacarte, let’s wait and see), but for the folders, I can’t see where they are created.

I can see where the name of the folder is computed (in [`storage/fs.py`](https://github.com/umap-project/umap/blob/master/umap/storage/fs.py#L60)), though.

**Comment by yohanboniface** [comment]
Ok, thanks for the feedback, I'll have a look!

I wonder why we never it that issue in other contexts…

For the record, here is how it is setup on the dev server (which also uses uvicorn, while the prod is still using uwsgi):

<img width="3840" height="137" alt="Image" src="https://github.com/user-attachments/assets/0df72824-2d0c-4fb5-a704-ab15790b4e6d" />

<img width="2032" height="283" alt="Image" src="https://github.com/user-attachments/assets/72ffc27d-cb63-4f0f-966f-c150eaa2c8b5" />

**Comment by ldidry** [comment]
Which user is used by nginx? Also : `.geojson` files are ok, it’s `.geojson.gz` that have bad permissions (you only showed `.geojson` files)

**Comment by yohanboniface** [comment]
>Which user is used by nginx?

<img width="2787" height="187" alt="Image" src="https://github.com/user-attachments/assets/df1d7046-bfb8-4feb-a3fb-1a171b2841f4" />




>  .geojson files are ok, it’s .geojson.gz that have bad permissions (you only showed .geojson files)

Ah, right!

<img width="2116" height="545" alt="Image" src="https://github.com/user-attachments/assets/59012011-bd32-4cf0-9a27-b64547301417" />

**Comment by ldidry** [comment]
I really have the strangest behavior. Here’s some outputs of a script which fixes the permission every minute (the different sections are the `find` arguments, to know what I’m looking at):
```
# -type f \! -perm -g+r
# -type d \! -perm -g+x
drwx------ 2 umap www-data 4.0K Sep 29 12:15 /var/www/umap/var/uploads/datalayer/3/2/215823
# -type d \! -perm -o+x
drwx------ 2 umap www-data 4.0K Sep 29 12:15 /var/www/umap/var/uploads/datalayer/3/2/215823
```

```
# -type f \! -perm -g+r
-rw------- 1 umap www-data 530 Sep 19 15:06 /var/www/umap/var/uploads/datalayer/8/6/215268/242b91b9-87c2-40e9-9102-6c6835ccec8b_1758287196041.geojson.gz
-rw------- 1 umap www-data 1.5K Sep 19 15:06 /var/www/umap/var/uploads/datalayer/8/6/215268/5852baa0-14d4-4fe5-b82e-e515b98d2923_1758287196307.geojson.gz
# -type d \! -perm -g+x
# -type d \! -perm -o+x
```

```
# -type f \! -perm -g+r
-rw------- 1 umap www-data 3.2K Sep 29 12:06 /var/www/umap/var/uploads/datalayer/0/6/192060/ccb3c086-d803-452d-a4d2-a4d1b3d752cc_1759140384928.geojson.gz
-rw------- 1 umap www-data 750 Sep 29 12:03 /var/www/umap/var/uploads/datalayer/1/7/214471/8288455a-2bf5-425c-a259-464c799c06cc_1759140213675.geojson.gz
# -type d \! -perm -g+x
drwx------ 2 umap www-data 4.0K Sep 29 12:23 /var/www/umap/var/uploads/datalayer/4/2/215824
# -type d \! -perm -o+x
drwx------ 2 umap www-data 4.0K Sep 29 12:23 /var/www/umap/var/uploads/datalayer/4/2/215824
```

**Comment by ldidry** [comment]
Note that sometimes… it works! Like, the `.gz` permissions are good. Sometimes, not. And most of it, note that I added `os.chmod(to_path, stat.S_IRGRP)` in the `gzip_file` function of `utils.py`!

As for the folders permissions… 🤷

**Comment by yohanboniface** [comment]
Can you remember when / after which uMap version change this problem started ?

**Comment by ldidry** [comment]
When uvicorn was introduced, I think. Strange thing: no problem with our beta site 😭

**Comment by ldidry** [comment]
Thx! 🤗
